server:
  port: 8080

spring:
  application:
    name: forum-backend
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/forum}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

app:
  security:
    allowedEmailDomain: ${ALLOWED_EMAIL_DOMAIN:your-college-domain.tld}
    jwt:
      issuer: forum
      accessTtl: 15m
      refreshTtl: 7d
      public-key-location: classpath:keys/jwt.pub
      private-key-location: classpath:keys/jwt.key
      audience: forum-clients

cors:
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000}


